from datetime import datetime
from app.models import ProjectRequirements, ColorPreference, Typography

STARTER_PROJECTS = [
    ProjectRequirements(
        id="starter-india-festivals",
        name="Utsav India",
        domain="utsavindia.com",
        category="Cultural Heritage & Festivals",
        websiteType="Blog",
        country="India",
        language="English",
        primaryAudience="Global Indian Diaspora, Cultural Enthusiasts & Travelers",
        brandStyle="Modern & Vibrant",
        colorPreference=ColorPreference(primary="#f97316", secondary="#1e293b", accent="#eab308"),
        typography=Typography(heading="Outfit", body="Inter"),
        primaryKeyword="Indian Festivals",
        secondaryKeywords=["Diwali Rituals", "Holi Colors Science", "Navratri Garba Guide", "Durga Puja Pandals", "Eco-friendly Diwali"],
        numberPages=8,
        needBlog=True,
        needAdminPanel=True,
        needDatabase=True,
        needAuth=True,
        needSearch=True,
        needCategories=True,
        needTags=True,
        needContactForm=True,
        needNewsletter=True,
        needFaq=True,
        needTestimonials=False,
        needAnalytics=True,
        needAds=True,
        needCookieConsent=True,
        needDarkMode=True,
        needRssFeed=True,
        needSitemap=True,
        needRobots=True,
        needSocialSharing=True,
        createdAt=datetime.utcnow().isoformat() + "Z"
    ),
    ProjectRequirements(
        id="starter-fintech-hub",
        name="FinTech Pulse",
        domain="fintechpulse.io",
        category="Finance & Technology",
        websiteType="Magazine",
        country="United States",
        language="English",
        primaryAudience="Tech Leaders, Investors, Financial Analysts & Developers",
        brandStyle="Dark & Glassmorphism",
        colorPreference=ColorPreference(primary="#6366f1", secondary="#0f172a", accent="#38bdf8"),
        typography=Typography(heading="Inter", body="Fira Code"),
        primaryKeyword="Open Banking API",
        secondaryKeywords=["Embedded Finance", "AI Wealth Management", "Blockchain Security", "Stripe Integration API", "RegTech Trends"],
        numberPages=10,
        needBlog=True,
        needAdminPanel=True,
        needDatabase=True,
        needAuth=True,
        needSearch=True,
        needCategories=True,
        needTags=True,
        needContactForm=True,
        needNewsletter=True,
        needFaq=True,
        needTestimonials=True,
        needAnalytics=True,
        needAds=True,
        needCookieConsent=True,
        needDarkMode=True,
        needRssFeed=True,
        needSitemap=True,
        needRobots=True,
        needSocialSharing=True,
        createdAt=datetime.utcnow().isoformat() + "Z"
    ),
    ProjectRequirements(
        id="starter-health-wellness",
        name="AyurLife Daily",
        domain="ayurlifedaily.com",
        category="Health & Wellness",
        websiteType="Portal",
        country="United Kingdom",
        language="English",
        primaryAudience="Wellness Seekers, Holistic Living Practitioners & Nutritionists",
        brandStyle="Clean & Minimalist",
        colorPreference=ColorPreference(primary="#10b981", secondary="#1f2937", accent="#06b6d4"),
        typography=Typography(heading="Outfit", body="Inter"),
        primaryKeyword="Ayurvedic Wellness",
        secondaryKeywords=["Holistic Nutrition Guide", "Herbal Immunity Boosters", "Mindful Meditation Daily", "Seasonal Dosha Balance"],
        numberPages=7,
        needBlog=True,
        needAdminPanel=False,
        needDatabase=True,
        needAuth=False,
        needSearch=True,
        needCategories=True,
        needTags=True,
        needContactForm=True,
        needNewsletter=True,
        needFaq=True,
        needTestimonials=False,
        needAnalytics=True,
        needAds=True,
        needCookieConsent=True,
        needDarkMode=True,
        needRssFeed=True,
        needSitemap=True,
        needRobots=True,
        needSocialSharing=True,
        createdAt=datetime.utcnow().isoformat() + "Z"
    )
]
